title: DNS Response Validator
logo: /_media/LICENSE
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - globals.md
  - interfaces
  - functions
  - variables
  - _media
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
