name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version bump type (patch, minor, major, prerelease, none)'
        required: false
        default: 'patch'
      preid:
        description: 'Prerelease identifier (used only when bump=prerelease)'
        required: false
        default: 'rc'

permissions:
  contents: write
  packages: write
  id-token: write # required for npm provenance

jobs:
  auto-tag:
    name: Auto create tag (manual dispatch)
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && !startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 18

      - name: Configure Git User
        run: |
          git config user.name "nick2bad4u"
          git config user.email "nick2bad4u@users.noreply.github.com"

      - name: Create tag from package.json version if missing
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          BUMP="${{ github.event.inputs.bump }}"
          PREID="${{ github.event.inputs.preid }}"
          echo "Requested bump: ${BUMP:-patch}"
          git fetch --tags --quiet
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version: ${CURRENT_VERSION}"
          if [ -z "$BUMP" ]; then BUMP=patch; fi
          if [ "$BUMP" = "none" ]; then
            TAG="v${CURRENT_VERSION}"
            if git rev-parse -q --verify "refs/tags/${TAG}" >/dev/null; then
              echo "Tag ${TAG} already exists. Nothing to do."
              exit 0
            fi
            echo "Creating tag ${TAG} without version bump"
            git tag -a "${TAG}" -m "Release ${TAG}"
            git push origin "${TAG}"
            echo "Tag ${TAG} pushed. New workflow run will publish."
            exit 0
          fi
          # Perform version bump
          if [ "$BUMP" = "prerelease" ]; then
            echo "Running prerelease bump with preid=${PREID}"
            npm version prerelease --preid "$PREID" -m "chore(release): v%s"
          else
            echo "Running npm version $BUMP"
            npm version "$BUMP" -m "chore(release): v%s"
          fi
          NEW_VERSION=$(node -p "require('./package.json').version")
            TAG="v${NEW_VERSION}"
          echo "New version: ${NEW_VERSION} (tag ${TAG})"
          git push origin HEAD:main --follow-tags
          echo "Pushed commit and tag ${TAG}. A new workflow run will publish the release."

  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 18
          cache: npm
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Type Check
        run: npm run typecheck

      - name: Tests & Coverage
        run: npm run test:coverage
        continue-on-error: true

      - name: Build
        run: npm run build

      - name: Verify package contents
        run: npm pack --dry-run

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --provenance --access public
        continue-on-error: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@6da8fa9354ddfdc4aeace5fc48d7f679b5214090 # v2.4.1
        with:
          generate_release_notes: true
          tag_name: ${{ github.ref_name }}
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-gpr:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: publish-npm

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 18
          cache: npm
          registry-url: https://npm.pkg.github.com
          scope: '@${{ github.repository_owner }}'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Rewrite package name for GPR
        run: |
          node -e "const fs=require('fs');const pkg=JSON.parse(fs.readFileSync('package.json','utf8'));pkg.name='@'+process.env.OWNER+'/'+pkg.name;delete pkg.publishConfig;fs.writeFileSync('package.json',JSON.stringify(pkg,null,2));"
        env:
          OWNER: ${{ github.repository_owner }}

      - name: Publish to GPR
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm publish --provenance
        continue-on-error: true
